app = 'FIXME'
primary_region = 'sea'

[build]

[env]
  WTT_DB_FILE = '/data/data.sqlite'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
