app = 'FIXME'
primary_region = 'sea'

[build]

[env]
  WTT_DB_FILE = '/data/data.sqlite'
  WTT_EXCLUDE_HEADERS = 'x-request-start,fly-client-ip,x-forwarded-for,fly-forwarded-proto,x-forwarded-proto,fly-forwarded-ssl,x-forwarded-ssl,fly-forwarded-port,x-forwarded-port,fly-region,fly-request-id,fly-tracestate,fly-traceparent,via'

[[mounts]]
  source = 'data'
  destination = '/data'

# Webhook responder
[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

# Admin server
[[services]]
  internal_port = 3001
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8000
