name: publish-release
run-name: Publish Release
on:
  push:
    branches: ["main"]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/checkout@v4
      - run: "bun ci"
      - run: "bun test"
      - run: "bun run build"
      - run: "bun run bakery release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Don't publish for now
      # - run: "bun run bakery publish"
      #   env:
      #     NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
